export const REPORT_CONTENT = `# summary

The intersection of esports and football in Southeast Asia represents a dynamic and rapidly evolving market landscape, marked by the convergence of traditional sports enthusiasm and burgeoning digital gaming trends. This intersection is notable for transforming how sports are perceived and engaged within the region, providing unique opportunities for market expansion and brand partnerships. The Southeast Asian market, characterized by distinct dynamics in countries such as Indonesia, Thailand, Vietnam, Malaysia, and the Philippines, reflects a blend of cultural traditions and modern technological advancements that are reshaping audience engagement across these sports sectors.
Football has historically been a dominant sport in Southeast Asia, deeply rooted in the cultural fabric of countries like Indonesia and Thailand. The passion for football in these countries is reflected in large, active fan bases, with Indonesia alone boasting over 300 million football enthusiasts.[1] Meanwhile, the Philippines offers a unique sporting environment where basketball rivals football in popularity, demonstrating the diverse sporting preferences within the region.[2] The rise of esports adds another dimension to Southeast Asia's sports landscape, evolving from a niche pastime to a multi-billion-dollar industry that attracts a growing competitive gaming community.[3][4] This digital engagement is significantly impacting traditional sports markets, prompting innovative strategies for audience engagement and market growth.[5][6]
Each Southeast Asian country exhibits unique growth patterns and engagement strategies within the esports and football markets. Thailand's esports market is expanding rapidly, driven by increased youth participation and a vibrant tournament scene.[7] In contrast, Vietnam's market growth is more subdued but supported by active government backing for esports as part of its digital economy strategy.[8] Indonesia stands out as a mobile esports leader, benefiting from a digitally-savvy population that drives substantial viewership numbers.[9][10] Malaysia and the Philippines show promising growth prospects, with Malaysia focusing on integrating esports into traditional sports frameworks and the Philippines achieving high revenue figures in the esports sector.[11][12]
The future of the intersection between esports and football in Southeast Asia is poised for substantial growth, with the region expected to become a major force in the global esports market.[13] This growth is fueled by strategic partnerships, increasing digital engagement, and governmental support across various countries. As esports continues to gain mainstream acceptance, the integration with football offers innovative opportunities for audience engagement, potentially transforming traditional sports marketing strategies and expanding market presence within Southeast Asia.[14][15]

# Historical Background

The intersection of esports and football in Southeast Asia has a diverse and rich history that varies by country. Football has long been a popular sport in the region, with countries like Indonesia, Malaysia, Thailand, and Vietnam leading the mass audience of football fans, totaling over 300 million active participants[1]. The passion for football in Southeast Asia is deeply rooted in cultural traditions and historical development.
In Thailand, football was introduced in 1897 by Siamese-English students and rapidly gained popularity among royal students and the military[16]. This early introduction helped establish football as a prominent sport within the country's cultural fabric. Meanwhile, in Indonesia, the development of the men's football team reflects significant historical eras, from the colonization era (1921-1938) to being Asia's first World Cup participant (1938-1945), through the independence era (1945-1984) and the renaissance period (1985-1995)[17].
Contrasting with other Southeast Asian countries, the Philippines demonstrates a unique sporting preference, where basketball enjoys as much popularity as football does in other parts of the region[2]. Basketball has played a significant role in shaping the cultural and social unity within the Philippines, transcending its colonial roots to create a lasting global impact through teams like Gilas Pilipinas[18].
The rise of esports in Southeast Asia adds another layer to the region's sports landscape. Esports has evolved from a niche pastime into a multi-billion-dollar market, offering new opportunities for brand partnerships and market expansion[3][4]. In countries like Thailand, esports is rapidly growing, with local players achieving success in international tournaments[19]. This growth presents significant investment opportunities and is transforming how traditional sports markets, such as football, are perceived and engaged with[5][6].
The convergence of esports and football in Southeast Asia reflects a dynamic blend of historical influences and modern technological advancements, paving the way for innovative sports marketing strategies and expanded audience engagement across the region.

# Market Dynamics

The intersection of the esports and football markets in Southeast Asia is characterized by distinct dynamics in each country, reflecting varied growth rates, audience engagement, and market strategies.
In Thailand, the esports market is experiencing robust growth driven by increased youth engagement and a burgeoning competitive gaming community[7]. This market's expansion is supported by a surge in popularity of tournaments and events, catering to an ever-growing audience[7].
Vietnam's esports market, although experiencing slower growth, is witnessing a rise in sponsorship and advertising, largely due to the increased popularity of digital platforms[20]. Despite its subdued growth influenced by limited sponsorships and consumer spending[21], the market is projected to grow significantly in the coming years, potentially reaching US$7.2 million by 2025[21].
Indonesia presents a mixed scenario where the esports market has been growing at a modest rate due to factors like limited sponsorship and advertising opportunities[22]. However, the country's esports industry is poised for continuous revenue increase, expected to climb by 30.77% between 2024 and 2029[23]. Indonesia's position as a global powerhouse in esports is bolstered by the rapid growth of viewership[9].
The Philippines shows promising potential in its esports market, with projected revenues of US$27.7 million by 2025[24]. The country's sports and esports industries are thriving, buoyed by several competitive advantages that fuel sectoral growth[11].
Malaysia has also seen a steady rise in esports awareness and familiarity, with peak awareness reaching 89% in the first two quarters of 2024[25]. The esports market in Malaysia is anticipated to grow, with revenue projected to reach US$6.8 million by 2025[26].
The overall Southeast Asian esports market has shown impressive growth, with revenues increasing at a compound annual growth rate (CAGR) of 20.8% from 2019 to 2024, significantly outpacing the global esports revenue growth rate[13]. The convergence of esports and football in this region reflects a transformative landscape where traditional sports fandom and digital engagement coexist, presenting opportunities for brands to capitalize on this dynamic market[4].

# Country-specific Analysis

## Indonesia

Indonesia has emerged as a significant player in the esports landscape, particularly within the mobile esports scene, which has attracted impressive viewership numbers[10]. With more than 52 million people participating in esports gaming, the country has developed a large cultural platform that offers numerous opportunities for key players in the industry[27]. Indonesia's esports achievements were highlighted during the 32nd Southeast Asian Games in Phnom Penh, where the Indonesian team secured three gold and two silver medals[9]. Additionally, the nation has a passionate football fan base, with over 300 million active enthusiasts[1], and football is deeply ingrained in Indonesian culture[28].

## Thailand

Thailand stands as a significant player in the global esports stage, driven by promising prospects for future growth[29]. The country ranks high in esports engagement, with 60.9% of respondents participating in esports activities[30]. Thailand's esports market is experiencing a surge in popularity, evidenced by an increasing number of tournaments and events[7]. The nation's football market is also notable, with the Thai League being the highest soccer league in the country[31], and Thailand holding the top position in FIFA Men's football ranking among Southeast Asian countries as of July 2024[32].

## Vietnam

Vietnam is characterized by a unique approach to esports, with active government support for esports as part of its digital economy strategy[8]. This support is crucial given the subdued growth of the esports market, which faces challenges such as limited sponsorships and low consumer spending on merchandise and tickets[21]. Football esports competitions have garnered interest among Vietnamese football fans, with 20% of surveyed fans expressing a desire to participate[33]. Furthermore, Vietnam's sports scene is rapidly growing, bolstered by passionate fans and substantial support from both the government and private sector[34].

## Malaysia

Malaysia's esports scene is evolving, with participation in major traditional sporting competitions such as the Asian Games and SEA Games[35]. However, Malaysia ranks at the bottom in terms of revenue in the esports market, showing a stark difference compared to other regional leaders[36]. Football in Malaysia is undergoing a transition phase, with the country's significant achievement being participation in the 2023 Asian Cup Finals[37]. Despite this transitional period, Malaysia remains engaged in both esports and football markets, providing opportunities for further development.

## Philippines

The Philippines is recognized as one of the key esports and gaming markets to watch in Asia, with esports being one of the fastest-growing sports in the country[11]. The nation ranks at 57.8% in terms of esports participation[30], and the revenue ranking in the esports market is led by the Philippines with 27.7 million U.S. dollars[12]. The country's passion for sports extends beyond esports, as basketball holds a significant cultural and unifying role, from colonial roots to the global impact of Gilas Pilipinas[18]. Football markets are projected to grow by 2.48% from 2025 to 2029[38], indicating promising prospects for the intersection of esports and traditional sports in the Philippines.

# Comparative Analysis

The intersection of esports and football in Southeast Asia presents a unique landscape that varies significantly across different countries, each with its distinct characteristics and growth patterns.

## Thailand

In Thailand, both esports and football enjoy significant popularity, with the government's active investment playing a crucial role in their growth. Football, deeply ingrained in Thai culture, has seen a rise in popularity, largely attributed to the national team's success[39]. On the other hand, esports is witnessing a rise, driven by increasing digital engagement and government support, offering various opportunities for investors[29].

## Malaysia

Malaysia presents a dynamic interaction between esports and traditional sports, including football. The country is experiencing a transition phase in football, marked by its participation in international tournaments like the 2023 Asian Cup Finals[37]. Concurrently, the esports sector in Malaysia is buoyed by a supportive governmental framework and a growing youthful demographic keen on digital entertainment[40][41]. This dual growth reflects a blend of traditional sporting enthusiasm and modern digital gaming trends.

## Indonesia

Indonesia stands out as a leading market for mobile gaming in Southeast Asia, accounting for a substantial portion of game downloads in the region[42]. While football remains a beloved sport, especially at the grassroots level, esports is rapidly gaining ground, benefiting from the country's large, digitally-savvy population[42]. This digital pivot indicates a potential shift in consumer engagement from traditional sports to digital platforms.

## Vietnam

Vietnam's esports and football sectors are shaped by the country's distinct cultural identity and the globalization of gaming habits. Football remains a popular sport, with the country's unique play culture offering new leisure experiences[43]. Meanwhile, esports is emerging as a vibrant sector, aligning with global gaming consumption trends and offering new avenues for engagement beyond traditional sports[43].

## The Philippines

The Philippines is witnessing substantial growth in both sports and esports industries, underpinned by competitive advantages such as a young, tech-savvy population[11]. Football is gaining more visibility through increased sports coverage, enhancing the profile of athletes and sporting events[44]. Esports is thriving, providing a dynamic arena for both economic and non-economic pursuits, reflecting the country's broader digital engagement[11][45].

# Future Prospects

The future prospects for the intersection of esports and football markets in Southeast Asia are promising, driven by substantial growth potential and strategic partnerships. In the Philippines, the sports and esports industries are thriving, with the country leveraging its competitive advantages to fuel growth in these sectors[11]. As football in the Philippines continues to develop, it will require years of collective effort to realize its potential fully[46].
Southeast Asia, as a region, is expected to become a major force driving the global esports market, with a projected market size of nearly US$30 billion by 2025[13]. The growth rate of esports revenues in Southeast Asia, at a CAGR of 20.8% from 2019 to 2024, demonstrates a robust expansion nearly double the global average[13]. Indonesia's esports market is expected to grow at a CAGR of 5.87%, with revenue forecasted to increase by 3.4 million US dollars between 2024 and 2029[47][23]. Similarly, Vietnam's esports market is projected to grow at a CAGR of 10.13% during 2024-2032, fueled by the increasing trend of gamers broadcasting their gameplay[48].
The involvement of national television in Vietnam's esports industry indicates a growing acceptance and mainstreaming of esports within the country[49][50]. Furthermore, regional policymakers are positioned to consider strategies that promote the esports gaming industry in Southeast Asia and Asia, fostering collaboration and protection[45][51]. The establishment of partnerships and sponsorships across major Asian cities will further drive the promotion and development of esports, thereby enriching the intersection with the football market[14][51].
In Malaysia, the dynamic esports landscape offers numerous opportunities for brands to engage with popular games and the growing audience[41]. The expected revenue growth in Malaysia's Sports & Outdoor market demonstrates a potential spillover effect benefiting the esports sector[52]. As esports creates meaningful touchpoints for fans across Thailand through grassroots programs and immersive in-game content, there is an opportunity for football to integrate and enhance its market presence through similar initiatives[15].`;
